no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Atomic" = 2
"Balance/Rebalance" = -4
"Code Improvement" = 2
<<<<<<< HEAD
"Feature" = -4
=======
"Mechanic" = -10
>>>>>>> 3d9180c33f0 (Adds content expansion PR type (#59152))
"Feedback" = 2
"Fix" = 4
"Grammar and Formatting" = 1
"Logging" = 1
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
<<<<<<< HEAD
"Quality of Life" = 2
=======
"Quality of Life" = 1
"Content Expansion" = -3
>>>>>>> 3d9180c33f0 (Adds content expansion PR type (#59152))
"Refactor" = 10
"Sound" = 3
"Sprites" = 3
"Unit Tests" = 6
