no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Accessibility" = 3
"Administration" = 2
"Atomic" = 2
"Balance/Rebalance" = -5
"Code Improvement" = 2
"Feedback" = 2
"Fix" = 4
"Grammar and Formatting" = 1
"Hard Deletes" = 12
"Logging" = 1
<<<<<<< HEAD
"Mechanic" = -12
=======
"Feature" = -6
>>>>>>> 93f39af8ac7 (removes the Content Expansion tag, replaces Mechanic with Feature, and lowers its gbp cost from 10 to 6 (#66425))
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
"Quality of Life" = 2
"Refactor" = 10
"Sound" = 3
"Sprites" = 3
"Unit Tests" = 6
