directory = "_maps/skyrat/deepmaint/templates"

[rooms.factory_entrance]
modules = ["factory_entrance.dmm", "factory_entrance_campsite.dmm", "factory_entrance_closed.dmm", "factory_entrance_closets.dmm", "factory_entrance_containers.dmm", "factory_entrance_small_office.dmm"]
