directory = "_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/"

[rooms.cave]
modules = ["cave_xenos.dmm", "cave_rich.dmm", "cave_dugout.dmm"]

[rooms.xeno]
modules = ["xeno_safe.dmm", "xeno_dead.dmm", "xeno_nest.dmm"]

[rooms.cargo]
modules = ["cargo_stock.dmm", "cargo_warehouse"]
