name: Update TGS DMAPI

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-dmapi:
    runs-on: ubuntu-latest
    name: Update the TGS DMAPI
    steps:
    - uses: tgstation/tgs-dmapi-updater@v1.0.5
      with:
        header-path: 'code/__DEFINES/tgs.dm'
        library-path: 'code/modules/tgs'
